// ─── Zone Loot Composition ──────────────────────────────────────────
//
// Deterministic loot count enforcement. Pairs with zoneRebalance.ts —
// rebalance restates whatever items exist; this fills in the gaps so the
// zone ships with a sensible loot table (one epic per class, N rares per
// class, plus an unrestricted uncommon/common pool).
//
// Generated items are intentionally thin placeholders ("Epic Warrior
// Greaves" + autogenerated description). The point is to ship a zone with
// a complete, balanced loot table at generation time; renaming and
// authoring proper descriptions is a builder step. Look for IDs starting
// with `gen_` to find them.

import type { AppConfig } from "@/types/config";
import type { ItemFile, MobDropFile, MobFile, WorldFile } from "@/types/world";
import type { ItemTier } from "./tuning/itemBudget";
import {
  inferLevelBand,
  restatItem,
  targetLevelForItemTier,
} from "./zoneRebalance";

export interface LootCompositionRules {
  /** Number of items required at each tier, per class. */
  perClassByTier: {
    epic: number;
    rare: number;
  };
  /** Number of unrestricted items required at each tier (shared across classes). */
  poolByTier: {
    uncommon: number;
    common: number;
  };
}

export const DEFAULT_LOOT_RULES: LootCompositionRules = {
  perClassByTier: { epic: 1, rare: 2 },
  poolByTier: { uncommon: 6, common: 10 },
};

export interface LootCompositionSummary {
  itemsAdded: number;
  epicAdded: number;
  rareAdded: number;
  uncommonAdded: number;
  commonAdded: number;
  dropsAdded: number;
  /** True when player-scaled zone short-circuited — no items added. */
  playerScaledNoOp: boolean;
}

export interface LootCompositionResult {
  world: WorldFile;
  summary: LootCompositionSummary;
}

// ─── Templates / labels ────────────────────────────────────────────

const EQUIP_SLOT_CYCLE = ["weapon", "chest", "head", "legs", "feet", "hands"] as const;

const DROP_CHANCE: Record<ItemTier, number> = {
  legendary: 0.05,
  epic: 0.10,
  rare: 0.20,
  uncommon: 0.40,
  common: 0.60,
  trash: 0.80,
};

const SLOT_LABEL: Record<string, string> = {
  weapon: "Blade",
  chest: "Cuirass",
  head: "Helm",
  legs: "Greaves",
  feet: "Boots",
  hands: "Gauntlets",
};

const TIER_LABEL: Record<ItemTier, string> = {
  legendary: "Legendary",
  epic: "Epic",
  rare: "Rare",
  uncommon: "Uncommon",
  common: "Common",
  trash: "Trash",
};

function titleCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

function buildItemId(
  takenIds: Set<string>,
  tier: ItemTier,
  className: string | null,
  slot: string,
): string {
  const base = className
    ? `gen_${tier}_${className.toLowerCase()}_${slot}`
    : `gen_${tier}_${slot}`;
  if (!takenIds.has(base)) return base;
  let n = 2;
  while (takenIds.has(`${base}_${n}`)) n++;
  return `${base}_${n}`;
}

function makePlaceholderItem(
  tier: ItemTier,
  classRestriction: string | null,
  slot: string,
): ItemFile {
  const slotLabel = SLOT_LABEL[slot] ?? titleCase(slot);
  const classFragment = classRestriction ? `${titleCase(classRestriction)} ` : "";
  return {
    displayName: `${TIER_LABEL[tier]} ${classFragment}${slotLabel}`,
    description: `Autogenerated ${tier}-tier ${slot} for this zone. Replace the name and description, then keep editing.`,
    slot,
    tier,
    classes: classRestriction ? [classRestriction] : undefined,
  };
}

// ─── Drop placement ─────────────────────────────────────────────────

/**
 * Find a combat mob to host a drop, preferring tiers in order. Rotates
 * across candidates so multiple drops at the same tier spread across mobs
 * instead of piling onto a single boss.
 */
function pickDropTarget(
  mobs: Record<string, MobFile>,
  preferredTiers: readonly string[],
  rotationIndex: number,
): string | null {
  for (const tier of preferredTiers) {
    const candidates = Object.entries(mobs)
      .filter(([, m]) => (m.role ?? "combat") === "combat" && (m.tier ?? "standard") === tier)
      .map(([id]) => id);
    if (candidates.length > 0) {
      return candidates[rotationIndex % candidates.length] ?? null;
    }
  }
  const anyCombat = Object.entries(mobs)
    .filter(([, m]) => (m.role ?? "combat") === "combat")
    .map(([id]) => id);
  return anyCombat.length > 0 ? anyCombat[rotationIndex % anyCombat.length] ?? null : null;
}

function appendDrop(mob: MobFile, drop: MobDropFile): MobFile {
  return { ...mob, drops: [...(mob.drops ?? []), drop] };
}

// ─── Main entry ─────────────────────────────────────────────────────

/**
 * Enforce a deterministic loot composition on a zone. Fills gaps in the
 * "epic/rare per class" and "uncommon/common pool" counts without touching
 * existing items. Each generated item is restated through the item-budget
 * pipeline so stats are math-consistent, and is dropped onto a tier-
 * appropriate mob (boss/elite for epic, elite/standard for rare, etc.).
 *
 * Idempotent: rerunning with the same rules on a balanced zone is a no-op.
 * Player-scaled zones short-circuit (drops still work, but the per-tier
 * level placement is meaningless when mobs derive level at runtime).
 */
export function ensureLootComposition(
  world: WorldFile,
  config: AppConfig,
  classes: readonly string[],
  rules: LootCompositionRules = DEFAULT_LOOT_RULES,
): LootCompositionResult {
  if (world.scaling?.mode === "player") {
    return {
      world,
      summary: {
        itemsAdded: 0,
        epicAdded: 0,
        rareAdded: 0,
        uncommonAdded: 0,
        commonAdded: 0,
        dropsAdded: 0,
        playerScaledNoOp: true,
      },
    };
  }

  const normalizedClasses = Array.from(
    new Set(classes.map((c) => c.trim().toUpperCase()).filter(Boolean)),
  );
  const band = world.levelBand ?? inferLevelBand(world);
  // Per-slot budget overrides aren't surfaced in EquipmentSlotDefinition yet,
  // so deriveItemStats uses its DEFAULT_SLOT_BASE_BUDGETS map. config is kept
  // in the signature for future expansion (custom slot budgets, builder-set
  // rule overrides) without a breaking change.
  void config;

  // Tally existing items by tier + class restriction.
  const existing = world.items ?? {};
  const epicByClass = new Map<string, number>();
  const rareByClass = new Map<string, number>();
  let uncommonPoolCount = 0;
  let commonPoolCount = 0;
  for (const item of Object.values(existing)) {
    const tier = item.tier;
    if (!tier) continue;
    if (tier === "epic") {
      for (const cls of item.classes ?? []) {
        epicByClass.set(cls, (epicByClass.get(cls) ?? 0) + 1);
      }
    } else if (tier === "rare") {
      for (const cls of item.classes ?? []) {
        rareByClass.set(cls, (rareByClass.get(cls) ?? 0) + 1);
      }
    } else if (tier === "uncommon" && (!item.classes || item.classes.length === 0)) {
      uncommonPoolCount++;
    } else if (tier === "common" && (!item.classes || item.classes.length === 0)) {
      commonPoolCount++;
    }
  }

  const nextItems: Record<string, ItemFile> = { ...existing };
  const nextMobs: Record<string, MobFile> = { ...(world.mobs ?? {}) };
  const takenIds = new Set(Object.keys(nextItems));

  let epicAdded = 0;
  let rareAdded = 0;
  let uncommonAdded = 0;
  let commonAdded = 0;
  let dropsAdded = 0;
  let slotIdx = 0;
  let mobRotation = 0;

  function addItem(
    tier: ItemTier,
    classRestriction: string | null,
    preferredMobTiers: readonly string[],
  ): void {
    const slot = EQUIP_SLOT_CYCLE[slotIdx++ % EQUIP_SLOT_CYCLE.length]!;
    const level = targetLevelForItemTier(tier, band);
    const id = buildItemId(takenIds, tier, classRestriction, slot);
    takenIds.add(id);
    const stub = makePlaceholderItem(tier, classRestriction, slot);
    nextItems[id] = restatItem(stub, level);

    const targetMobId = pickDropTarget(nextMobs, preferredMobTiers, mobRotation++);
    if (targetMobId) {
      nextMobs[targetMobId] = appendDrop(nextMobs[targetMobId]!, {
        itemId: id,
        chance: DROP_CHANCE[tier],
      });
      dropsAdded++;
    }
  }

  for (const cls of normalizedClasses) {
    const need = Math.max(0, rules.perClassByTier.epic - (epicByClass.get(cls) ?? 0));
    for (let i = 0; i < need; i++) {
      addItem("epic", cls, ["boss", "elite"]);
      epicAdded++;
    }
  }
  for (const cls of normalizedClasses) {
    const need = Math.max(0, rules.perClassByTier.rare - (rareByClass.get(cls) ?? 0));
    for (let i = 0; i < need; i++) {
      addItem("rare", cls, ["elite", "standard"]);
      rareAdded++;
    }
  }
  {
    const need = Math.max(0, rules.poolByTier.uncommon - uncommonPoolCount);
    for (let i = 0; i < need; i++) {
      addItem("uncommon", null, ["standard", "weak"]);
      uncommonAdded++;
    }
  }
  {
    const need = Math.max(0, rules.poolByTier.common - commonPoolCount);
    for (let i = 0; i < need; i++) {
      addItem("common", null, ["weak", "standard"]);
      commonAdded++;
    }
  }

  const itemsAdded = epicAdded + rareAdded + uncommonAdded + commonAdded;
  return {
    world: { ...world, items: nextItems, mobs: nextMobs },
    summary: {
      itemsAdded,
      epicAdded,
      rareAdded,
      uncommonAdded,
      commonAdded,
      dropsAdded,
      playerScaledNoOp: false,
    },
  };
}
